---
- hosts: localhost
  connection: local
  become: yes
  become_user: root
  become_method: su
  vars_files:
    - vhost-sc-s.yml
    - vhost-sc-a.yml
  tasks:
    - name: gitを最新版にするためのdevelをインストール
      with_items:
        - make
        - libcurl-devel
        - gcc
        - openssl-devel
        - expat-devel
        - gettext
        - asciidoc
        - xmlto
        - perl-ExtUtils-MakeMaker
        - autoconf
      yum: name={{ item }} state=installed

    - name: 最新版のgitをclone
      git: repo=git@github.com:git/git.git dest=/root/git accept_hostkey=yes

    - name: gitをmake configure
      command: make configure
      args:
        chdir: /root/git/

    - name: git prefix 付きでconfigure
      command: ./configure --prefix=/usr/local --with-curl --with-expat
      args:
        chdir: /root/git/

    - name: gitをmake all doc
      command: make all doc
      args:
        chdir: /root/git/

    - name: gitをmake install
      command: make install install-doc install-html
      args:
        chdir: /root/git/

    - name: localeの設定
      command: localectl set-locale LANG=ja_JP.utf8

    - name: timezoneの設定
      command: timedatectl set-timezone Asia/Tokyo

    - name: rootユーザーのsshを禁止する
      lineinfile:
        dest=/etc/ssh/sshd_config
        state=present
        regexp='#PermitRootLogin yes'
        line='PermitRootLogin no'
      notify: restart sshd

    - name: yum install httpd
      yum: name=httpd state=installed

    - name: httpd の起動と自動起動設定
      service: name=httpd state=running enabled=yes

    - name: firewallにhttpdを追加
      firewalld:
        service=http
        permanent=true
        state=enabled
        immediate=true

    - name: httpd.confをvirtualhost対応に
      lineinfile:
        dest=/etc/httpd/conf/httpd.conf
        state=present
        regexp="IncludeOptional conf.d/*.conf"
        line="IncludeOptional conf.d/vhost/*.conf"

    - name: httpd.confにNameVirtualHostを追加
      lineinfile:
        dest=/etc/httpd/conf/httpd.conf
        regexp="NameVirtualHost *:80"
        line="NameVirtualHost *:80"

    - name: vhostディレクトリの作成
      file: path=/etc/httpd/conf.d/vhost state=directory

    - name: virtualhostを作成
      template: src=template-vhost-sc-s.j2 dest=/etc/httpd/conf.d/vhost/smart-contact_service.conf
      notify: restart httpd

    - name: virtualhostを作成
      template: src=template-vhost-sc-a.j2 dest=/etc/httpd/conf.d/vhost/smart-contact_admin.conf
      notify: restart httpd

    - name: SELinuxの無効化　
      lineinfile:
        dest=/etc/selinux/config
        state=present
        regexp="SELINUX=enforcing"
        line="SELINUX=disabled"

  handlers:
    - name: restart sshd
      service: name=sshd state=restarted

    - name: restart httpd
      service: name=httpd state=restarted
